routes/web.php
<?php

use App\Http\Controllers\AccessController;
use App\Http\Controllers\CalonController;
use App\Http\Controllers\FrontController;
use App\Http\Controllers\HitungController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\LanguageController;
use App\Http\Controllers\SuaraCalonController;
use App\Http\Controllers\TpsController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\WilayahController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
  Route::get('/', [FrontController::class,'index'])->name('front');

  Auth::routes();

  // dashboard Routes
  Route::get('/home', [HomeController::class,'index'])->name('home');

  /*
   * Route Data Wilayah
   */
  Route::get('select-provinsi', [WilayahController::class,'getSelectProvinsi'])->name('select.prov');
  Route::get('select-kabupaten', [WilayahController::class,'getSelectKota'])->name('select.kota');
  Route::get('select-kecamatan', [WilayahController::class,'getSelectKecamatan'])->name('select.kecamatan');
  Route::get('select-kelurahan', [WilayahController::class,'getSelectDesa'])->name('select.desa');

  /*
   * Route Data TPS
   */
  Route::get('tps-list', [TpsController::class,'getTpsData'])->name('tps.list');
  Route::resource('data-tps', TpsController::class);

  //Route::view('tps', 'livewire.tps');
  Route::get('calon-list', [CalonController::class,'getCalonData'])->name('calon.list');
  Route::get('select-jeniscalon', [CalonController::class,'getSelectJenisCalon'])->name('select.jeniscalon');
  Route::resource('data-calon', CalonController::class);

  Route::get('input-suara-calon/{id}', 'SuaraCalonController@inputSuaraCalon')->name('suaracalon.input');
  Route::get('suaracalon-list', [SuaraCalonController::class,'getSuaraCalonData'])->name('suaracalon.list');
  Route::get('select-paslon', [SuaraCalonController::class,'getSelectPaslon'])->name('select.paslon');
  Route::get('select-tps', [SuaraCalonController::class,'getSelectTps'])->name('select.tps');
  Route::resource('data-suara-calon', SuaraCalonController::class);

  // Route Hitung Cepat
  Route::get('export', 'HitungController@export')->name('hitung.export');
  Route::get('hitung-suara', [HitungController::class,'getHitungSuaraData'])->name('hitungsuara.list');
  Route::resource('hitung-cepat', HitungController::class);

  //  Route::resource('/log-absen', 'LogController');

  Route::resource('pengguna', UserController::class);

  // locale Route
  Route::get('lang/{locale}', [LanguageController::class, 'swap']);

  // acess controller
  Route::get('/access-control',  [AccessController::class,'index']);
  Route::get('/access-control/{roles}', [AccessController::class,'roles']);
  Route::get('/ecommerce', [AccessController::class,'home'])->middleware('role:Admin');

  Route::get('/clear-cache', function () {
    Artisan::call('cache:clear');
  });
  Route::get('/clear-view', function () {
    Artisan::call('view:clear');
  });
  Route::get('/clear-optimize', function () {
    Artisan::call('optimize:clear');
  });

app/Models/User.php
<?php

  namespace App\Models;

  use Illuminate\Contracts\Auth\MustVerifyEmail;
  use Illuminate\Foundation\Auth\User as Authenticatable;
  use Illuminate\Notifications\Notifiable;
  use Laravolt\Indonesia\Models\Kabupaten;
  use Laravolt\Indonesia\Models\Kecamatan;
  use Laravolt\Indonesia\Models\Kelurahan;
  use Laravolt\Indonesia\Models\Provinsi;
  use Spatie\Permission\Traits\HasRoles;

  /**
 * @mixin IdeHelperUser
 */
  class User extends Authenticatable
  {
    use Notifiable, HasRoles;

    //protected $table = 'pengguna';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
      'name', 'username', 'email', 'password', 'last_login', 'is_superadmin', 'status', 'email_verified_at',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
      'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
      'email_verified_at' => 'datetime',
      'last_login' => 'datetime',
    ];


    public function provinsi()
    {
      return $this->hasOne(Provinsi::class, 'id', 'id');
    }

    public function kabupaten()
    {
      return $this->hasOne(Kabupaten::class,'id','id');
    }

    public function kecamatan()
    {
      return $this->hasOne(Kecamatan::class,'id','id');
    }

    public function kelurahan()
    {
      return $this->hasOne(Kelurahan::class,'id','id');
    }

    public function isSuperadmin($id)
    {
      return self::find($id) ? $this->is_superadmin : false;
    }
  }

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\View\View;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|Response|View
     */
    public function index()
    {
      $user = User::all();
        return view('pages.user.index',compact('user'));
    }

  /**
   * Show the form for creating a new resource.
   *
   * @return void
   */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return Response
     */
    public function store(Request $request)
    {
        //
    }

  /**
   * Display the specified resource.
   *
   * @param  int  $id
   * @return Application|Factory|Response|View
   */
    public function show(int $id)
    {
        return view('pages.user.detail')->with('id',$id);
    }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  int  $id
   * @return Application|Factory|Response|View
   */
    public function edit(int $id)
    {
        return view('pages.user.edit')->with('id',$id);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Livewire/User.php
<?php

  namespace App\Http\Livewire;

  use Livewire\Component;

  class User extends Component
  {
    public function render()
    {
      return view('livewire.user');
    }
  }

resources/views/pages/user/detail.blade.php
@extends('layouts.contentLayoutMaster')
{{-- title --}}
@section('title','Datatables')

{{-- vendor style --}}
@section('vendor-styles')
  <link rel="stylesheet" type="text/css" href="{{asset('vendors/css/tables/datatable/datatables.min.css')}}">
@endsection
{{-- page-styles --}}
@section('page-styles')
  <link rel="stylesheet" type="text/css" href="{{asset('css/pages/page-user.css')}}">
@endsection

@section('content')
  <!-- users view start -->
  <section class="users-view">
    <!-- users view media object start -->
    <div class="row">
      <div class="col-12 col-sm-7">
        <div class="media mb-2">
          <a class="mr-1" href="#">
            <img src="{{ asset('images/portrait/small/avatar-s-26.jpg') }}" alt="users view avatar" class="users-avatar-shadow rounded-circle" height="64" width="64">
          </a>
          <div class="media-body pt-25">
            <h4 class="media-heading"><span class="users-view-name">Dean Stanley </span><span class="text-muted font-medium-1"> @</span><span class="users-view-username text-muted font-medium-1 ">candy007</span></h4>
            <span>ID:</span>
            <span class="users-view-id">305</span>
          </div>
        </div>
      </div>
      <div class="col-12 col-sm-5 px-0 d-flex justify-content-end align-items-center px-1 mb-2">
        <a href="#" class="btn btn-sm mr-25 border"><i class="bx bx-envelope font-small-3"></i></a>
        <a href="#" class="btn btn-sm mr-25 border">Profile</a>
        <a href="{{ route('pengguna.edit',1) }}" class="btn btn-sm btn-primary">Edit</a>
      </div>
    </div>
    <!-- users view media object ends -->
    <!-- users view card data start -->
    <div class="card">
      <div class="card-content">
        <div class="card-body">
          <div class="row">
            <div class="col-12 col-md-4">
              <table class="table table-borderless">
                <tbody>
                <tr>
                  <td>Registered:</td>
                  <td>01/01/2019</td>
                </tr>
                <tr>
                  <td>Latest Activity:</td>
                  <td class="users-view-latest-activity">30/04/2019</td>
                </tr>
                <tr>
                  <td>Verified:</td>
                  <td class="users-view-verified">Yes</td>
                </tr>
                <tr>
                  <td>Role:</td>
                  <td class="users-view-role">Staff</td>
                </tr>
                <tr>
                  <td>Status:</td>
                  <td><span class="badge badge-light-success users-view-status">Active</span></td>
                </tr>
                </tbody>
              </table>
            </div>
            <div class="col-12 col-md-8">
              <div class="table-responsive">
                <table class="table mb-0">
                  <thead>
                  <tr>
                    <th>Module Permission</th>
                    <th>Read</th>
                    <th>Write</th>
                    <th>Create</th>
                    <th>Delete</th>
                  </tr>
                  </thead>
                  <tbody>
                  <tr>
                    <td>Users</td>
                    <td>Yes</td>
                    <td>No</td>
                    <td>No</td>
                    <td>Yes</td>
                  </tr>
                  <tr>
                    <td>Articles</td>
                    <td>No</td>
                    <td>Yes</td>
                    <td>No</td>
                    <td>Yes</td>
                  </tr>
                  <tr>
                    <td>Staff</td>
                    <td>Yes</td>
                    <td>Yes</td>
                    <td>No</td>
                    <td>No</td>
                  </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- users view card data ends -->
    <!-- users view card details start -->
    <div class="card">
      <div class="card-content">
        <div class="card-body">
          <div class="row bg-primary bg-lighten-5 rounded mb-2 mx-25 text-center text-lg-left">
            <div class="col-12 col-sm-4 p-2">
              <h6 class="text-primary mb-0">Posts: <span class="font-large-1 align-middle">125</span></h6>
            </div>
            <div class="col-12 col-sm-4 p-2">
              <h6 class="text-primary mb-0">Followers: <span class="font-large-1 align-middle">534</span></h6>
            </div>
            <div class="col-12 col-sm-4 p-2">
              <h6 class="text-primary mb-0">Following: <span class="font-large-1 align-middle">256</span></h6>
            </div>
          </div>
          <div class="col-12">
            <table class="table table-borderless">
              <tbody>
              <tr>
                <td>Username:</td>
                <td class="users-view-username">dean3004</td>
              </tr>
              <tr>
                <td>Name:</td>
                <td class="users-view-name">Dean Stanley</td>
              </tr>
              <tr>
                <td>E-mail:</td>
                <td class="users-view-email">deanstanley@gmail.com</td>
              </tr>
              <tr>
                <td>Comapny:</td>
                <td>XYZ Corp. Ltd.</td>
              </tr>

              </tbody>
            </table>
            <h5 class="mb-1"><i class="bx bx-link"></i> Social Links</h5>
            <table class="table table-borderless">
              <tbody>
              <tr>
                <td>Twitter:</td>
                <td><a href="#">https://www.twitter.com/</a></td>
              </tr>
              <tr>
                <td>Facebook:</td>
                <td><a href="#">https://www.facebook.com/</a></td>
              </tr>
              <tr>
                <td>Instagram:</td>
                <td><a href="#">https://www.instagram.com/</a></td>
              </tr>
              </tbody>
            </table>
            <h5 class="mb-1"><i class="bx bx-info-circle"></i> Personal Info</h5>
            <table class="table table-borderless mb-0">
              <tbody>
              <tr>
                <td>Birthday:</td>
                <td>03/04/1990</td>
              </tr>
              <tr>
                <td>Country:</td>
                <td>USA</td>
              </tr>
              <tr>
                <td>Languages:</td>
                <td>English</td>
              </tr>
              <tr>
                <td>Contact:</td>
                <td>+(305) 254 24668</td>
              </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
    <!-- users view card details ends -->

  </section>
  <!-- users view ends -->
  @include('widgets.modal')
@endsection
{{-- vendor scripts --}}
@section('vendor-scripts')
  <script src="{{asset('vendors/js/tables/datatable/datatables.min.js')}}"></script>
  <script src="{{asset('vendors/js/tables/datatable/dataTables.bootstrap4.min.js')}}"></script>
  {{--  <script src="{{asset('vendors/js/tables/datatable/dataTables.checkboxes.min.js')}}"></script>--}}
  {{--  <script src="{{asset('vendors/js/tables/datatable/dataTables.select.min.js')}}"></script>--}}
  {{--  <script src="{{asset('vendors/js/tables/jszip/dist/jszip.min.js')}}"></script>--}}
  {{--  <script src="{{asset('vendors/js/tables/datatable/dataTables.responsive.min.js')}}"></script>--}}
  {{--  <script src="{{asset('vendors/js/tables/datatable/dataTables.buttons.min.js')}}"></script>--}}
  {{--  <script src="{{asset('vendors/js/tables/datatable/buttons.html5.min.js')}}"></script>--}}
  {{--  <script src="{{asset('vendors/js/tables/datatable/buttons.print.min.js')}}"></script>--}}
  {{--  <script src="{{asset('vendors/js/tables/datatable/buttons.bootstrap.min.js')}}"></script>--}}
  {{--  <script src="{{asset('vendors/js/tables/datatable/pdfmake.min.js')}}"></script>--}}
  {{--  <script src="{{asset('vendors/js/tables/datatable/vfs_fonts.js')}}"></script>--}}
@endsection
{{-- page scripts --}}
@section('page-scripts')
  <script src="{{ asset('js/scripts/pages/page-user.js')}}"></script>
  <script>
    $(function () {
      // $('#btnTambah').on('click', function () {
      //     $('#createModal').on('show.bs.modal', function () {
      //         // alert('onShow event fired.');
      //     });
      // });
      // document.addEventListener('livewire:load', function () {
      //     window.livewire.on('tpsStore', () => {
      //         $('#create-modal').modal('hide');
      //     });
      // })

      /* Datatable data from database */

      // let groupingTable = $('.row-grouping').DataTable({
      //     "columnDefs": [{
      //         "visible": false,
      //         "targets": 2
      //     }],
      //     "order": [
      //         [2, 'asc']
      //     ],
      //     "displayLength": 10,
      //     "drawCallback": function(settings) {
      //         let api = this.api();
      //         let rows = api.rows({
      //             page: 'current'
      //         }).nodes();
      //         let last = null;
      //
      //         api.column(2, {
      //             page: 'current'
      //         }).data().each(function(group, i) {
      //             if (last !== group) {
      //                 $(rows).eq(i).before(
      //                     '<tr class="group"><td colspan="5">' + group + '</td></tr>'
      //                 );
      //
      //                 last = group;
      //             }
      //         });
      //     }
      // });

      {{--let tabelTps = $('#table-tps').DataTable({--}}
      {{--  // dom: 'Bfrtip',--}}
      {{--  processing: true,--}}
      {{--  serverSide: true,--}}
      {{--  ajax: {--}}
      {{--    url: '{!! route('tps.list') !!}'--}}
      {{--  },--}}
      {{--  // order: [--}}
      {{--  //     [1, 'asc']--}}
      {{--  // ],--}}
      {{--  // displayLength : 10,--}}
      {{--  columns: [--}}
      {{--    // {data: 'DT_RowIndex',searchable: false, orderable: false},--}}
      {{--    {data: 'id', name:'id'},--}}
      {{--    // {data: 'prov_id', name: 'prov_id', searchable: false, orderable: false},--}}
      {{--    // {data: 'kota_id', name: 'kota_id', searchable: false, orderable: false},--}}
      {{--    {data: 'kec_id', name: 'kec_id'},--}}
      {{--    {data: 'kel_id', name: 'kel_id'},--}}
      {{--    {data: 'nama_tps', name: 'nama_tps'},--}}
      {{--    // {data: 'jumlah_tps', name: 'jumlah_tps'},--}}
      {{--    {data: 'status', name: 'status'},--}}
      {{--    {data: 'action', name: 'action', searchable: false, orderable: false}--}}
      {{--  ],--}}
      {{--  columnDefs: [--}}
      {{--    {--}}
      {{--      "orderable": false,--}}
      {{--      // "targets": [0,3]--}}
      {{--    },--}}
      {{--  ],--}}
      {{--  --}}
      {{--});--}}
      // Grouping Tabel
      // $('#table-tps tbody').on('click', 'tr.group', function() {
      //     let currentOrder = tabelTps .order()[0];
      //     if (currentOrder[0] === 3 && currentOrder[1] === 'asc') {
      //         tabelTps.order([3, 'desc']).draw();
      //     }
      //     else {
      //         tabelTps.order([3, 'asc']).draw();
      //     }
      // });

      /* Lapor Kegiatan Pegawai Ajax */
      // btnLapor.click(function () {
      //     Swal.fire({
      //         // title: 'Lapor kegiatan anda sekarang ?',
      //         text: "Lapor kegiatan anda sekarang ?",
      //         type: 'question',
      //         showCancelButton: true,
      //         confirmButtonColor: '#3085d6',
      //         cancelButtonColor: '#d33',
      //         confirmButtonText: 'Lapor',
      //         showLoaderOnConfirm: true,
      //         preConfirm: () => {
      //             let a = document.getElementById('filter-tglharian').value;
      //             return $.post(base_url + `/pegawai/lapor-kegiatan?t=${a}`)
      //                 .then(response => {
      //                     if (!response.status && response.error === 1) {
      //                         Swal.showValidationMessage(
      //                             response.msg
      //                         );
      //                     }
      //                     return response;
      //                 })
      //         },
      //         allowOutsideClick: () => !Swal.isLoading()
      //     }).then((result) => {
      //         if (result.value) {
      //             Swal.fire({
      //                 text: `${result.value.msg}`,
      //                 type: 'success'
      //             });
      //             tabelKegiatan.DataTable().ajax.reload();
      //         }
      //     })
      // });
    });
  </script>
@endsection

resources/views/pages/user/index.blade.php
@extends('layouts.contentLayoutMaster')
{{-- title --}}
@section('title','Datatables')

{{-- vendor style --}}
@section('vendor-styles')
  <link rel="stylesheet" type="text/css" href="{{asset('vendors/css/tables/datatable/datatables.min.css')}}">
@endsection
{{-- page-styles --}}
@section('page-styles')
  <link rel="stylesheet" type="text/css" href="{{asset('css/pages/page-users.css')}}">
@endsection

@section('content')
  <!-- users list start -->
  <section class="users-list-wrapper">
    @include('widgets.filter')
    <div class="users-list-table">
      <div class="card">
        <div class="card-content">
          <div class="card-body">
            <!-- datatable start -->
            <div class="table-responsive">
              <table id="users-list-datatable" class="table">
                <thead>
                <tr>
                  <th>No</th>
                  <th>Username</th>
                  <th>Nama</th>
                  <th>role</th>
                  <th>Status</th>
                  <th>Aksi</th>
                </tr>
                </thead>
                <tbody>
                @foreach($user as $item)
                  <tr>
                    <td>{{ $item->id }}</td>
                    <td><a href="{{ route('pengguna.show', 1) }}">{{ $item->username }}</a></td>
                    <td>{{ $item->name }}</td>
                    <td>{{ $item->is_superadmin === 1 ? 'Admin' : 'Relawan' }}</td>
                    <td>
                      <span class="badge badge-light-{{ $item->status === 1 ? 'success' : 'danger' }}">
                        {{ $item->status === 1 ? 'Aktif' : 'Tidak Aktif' }}
                      </span>
                    </td>
                    <td>
                      <a href="{{ route('pengguna.edit',1) }}"><i class="bx bx-edit-alt"></i></a>
                      <a href="{{ route('pengguna.destroy',1) }}"><i class="bx bx-trash-alt"></i></a>
                    </td>
                  </tr>
                @endforeach
                </tbody>
              </table>
            </div>
            <!-- datatable ends -->
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- users list ends -->
  @include('widgets.modal')
@endsection
{{-- vendor scripts --}}
@section('vendor-scripts')
  <script src="{{asset('vendors/js/tables/datatable/datatables.min.js')}}"></script>
  <script src="{{asset('vendors/js/tables/datatable/dataTables.bootstrap4.min.js')}}"></script>
{{--  <script src="{{asset('vendors/js/tables/datatable/dataTables.checkboxes.min.js')}}"></script>--}}
{{--  <script src="{{asset('vendors/js/tables/datatable/dataTables.select.min.js')}}"></script>--}}
{{--  <script src="{{asset('vendors/js/tables/jszip/dist/jszip.min.js')}}"></script>--}}
{{--  <script src="{{asset('vendors/js/tables/datatable/dataTables.responsive.min.js')}}"></script>--}}
{{--  <script src="{{asset('vendors/js/tables/datatable/dataTables.buttons.min.js')}}"></script>--}}
{{--  <script src="{{asset('vendors/js/tables/datatable/buttons.html5.min.js')}}"></script>--}}
{{--  <script src="{{asset('vendors/js/tables/datatable/buttons.print.min.js')}}"></script>--}}
{{--  <script src="{{asset('vendors/js/tables/datatable/buttons.bootstrap.min.js')}}"></script>--}}
{{--  <script src="{{asset('vendors/js/tables/datatable/pdfmake.min.js')}}"></script>--}}
{{--  <script src="{{asset('vendors/js/tables/datatable/vfs_fonts.js')}}"></script>--}}
@endsection
{{-- page scripts --}}
@section('page-scripts')
{{--  <script src="{{ asset('js/scripts/pages/page-users.js')}}"></script>--}}
  <script>
    $(function () {
      $(document).ready(function () {

        // variable declaration
        var usersTable;
        var usersDataArray = [];
        // datatable initialization
        if ($("#users-list-datatable").length > 0) {
          usersTable = $("#users-list-datatable").DataTable({
            responsive: true,
            'columnDefs': [
              {
                "orderable": false,
                "targets": [5]
              }]
          });
        };
        // on click selected users data from table(page named page-users-list)
        // to store into local storage to get rendered on second page named page-users-view
        $(document).on("click", "#users-list-datatable tr", function () {
          $(this).find("td").each(function () {
            usersDataArray.push($(this).text().trim())
          })
          console.log(usersDataArray);
          localStorage.setItem("usersId", usersDataArray[0]);
          localStorage.setItem("usersUsername", usersDataArray[1]);
          localStorage.setItem("usersName", usersDataArray[2]);
          localStorage.setItem("usersRole", usersDataArray[3]);
          localStorage.setItem("usersStatus", usersDataArray[4]);
        })
        // render stored local storage data on page named page-users-view
        if (localStorage.usersId !== undefined) {
          $(".users-view-id").html(localStorage.getItem("usersId"));
          $(".users-view-username").html(localStorage.getItem("usersUsername"));
          $(".users-view-name").html(localStorage.getItem("usersName"));
          $(".users-view-role").html(localStorage.getItem("usersRole"));
          $(".users-view-status").html(localStorage.getItem("usersStatus"));
          // update badge color on status change
          if ($(".users-view-status").text() === "Tidak Aktif") {
            $(".users-view-status").toggleClass("badge-light-success badge-light-danger")
          }
          // update badge color on status change
          if ($(".users-view-status").text() === "Aktif") {
            $(".users-view-status").toggleClass("badge-light-success badge-light-warning")
          }
        }
        // page users list verified filter
        $("#users-list-verified").on("change", function () {
          var usersVerifiedSelect = $("#users-list-verified").val();
          usersTable.search(usersVerifiedSelect).draw();
        });
        // page users list role filter
        $("#users-list-role").on("change", function () {
          var usersRoleSelect = $("#users-list-role").val();
          // console.log(usersRoleSelect);
          usersTable.search(usersRoleSelect).draw();
        });
        // page users list status filter
        $("#users-list-status").on("change", function () {
          var usersStatusSelect = $("#users-list-status").val();
          // console.log(usersStatusSelect);
          usersTable.search(usersStatusSelect).draw();
        });
        // users language select
        if ($("#users-language-select2").length > 0) {
          $("#users-language-select2").select2({
            dropdownAutoWidth: true,
            width: '100%'
          });
        }
        // page users list clear filter
        $(".users-list-clear").on("click", function(){
          usersTable.search("").draw();
        })
        // users music select
        if ($("#users-music-select2").length > 0) {
          $("#users-music-select2").select2({
            dropdownAutoWidth: true,
            width: '100%'
          });
        }
        // users movies select
        if ($("#users-movies-select2").length > 0) {
          $("#users-movies-select2").select2({
            dropdownAutoWidth: true,
            width: '100%'
          });
        }
        // users birthdate date
        if ($(".birthdate-picker").length > 0) {
          $('.birthdate-picker').pickadate({
            format: 'mmmm, d, yyyy'
          });
        }
        // Input, Select, Textarea validations except submit button validation initialization
        if ($(".users-edit").length > 0) {
          $("input,select,textarea").not("[type=submit]").jqBootstrapValidation();
        }
      });

    });
  </script>
@endsection