routes/web.php
<?php

use App\Http\Controllers\AccessController;
use App\Http\Controllers\CalonController;
use App\Http\Controllers\FrontController;
use App\Http\Controllers\HitungController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\LanguageController;
use App\Http\Controllers\SuaraCalonController;
use App\Http\Controllers\TpsController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\WilayahController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
  Route::get('/', [FrontController::class,'index'])->name('front');

  Auth::routes();

  // dashboard Routes
  Route::get('/home', [HomeController::class,'index'])->name('home');

  /*
   * Route Data Wilayah
   */
  Route::get('select-provinsi', [WilayahController::class,'getSelectProvinsi'])->name('select.prov');
  Route::get('select-kabupaten', [WilayahController::class,'getSelectKota'])->name('select.kota');
  Route::get('select-kecamatan', [WilayahController::class,'getSelectKecamatan'])->name('select.kecamatan');
  Route::get('select-kelurahan', [WilayahController::class,'getSelectDesa'])->name('select.desa');

  /*
   * Route Data TPS
   */
  Route::get('tps-list', [TpsController::class,'getTpsData'])->name('tps.list');
  Route::resource('data-tps', TpsController::class);

  //Route::view('tps', 'livewire.tps');
  Route::get('calon-list', [CalonController::class,'getCalonData'])->name('calon.list');
  Route::get('select-jeniscalon', [CalonController::class,'getSelectJenisCalon'])->name('select.jeniscalon');
  Route::resource('data-calon', CalonController::class);

  Route::get('input-suara-calon/{id}', 'SuaraCalonController@inputSuaraCalon')->name('suaracalon.input');
  Route::get('suaracalon-list', [SuaraCalonController::class,'getSuaraCalonData'])->name('suaracalon.list');
  Route::get('select-paslon', [SuaraCalonController::class,'getSelectPaslon'])->name('select.paslon');
  Route::get('select-tps', [SuaraCalonController::class,'getSelectTps'])->name('select.tps');
  Route::resource('data-suara-calon', SuaraCalonController::class);

  // Route Hitung Cepat
  Route::get('export', 'HitungController@export')->name('hitung.export');
  Route::get('hitung-suara', [HitungController::class,'getHitungSuaraData'])->name('hitungsuara.list');
  Route::resource('hitung-cepat', HitungController::class);

  //  Route::resource('/log-absen', 'LogController');

  Route::resource('pengguna', UserController::class);

  // locale Route
  Route::get('lang/{locale}', [LanguageController::class, 'swap']);

  // acess controller
  Route::get('/access-control',  [AccessController::class,'index']);
  Route::get('/access-control/{roles}', [AccessController::class,'roles']);
  Route::get('/ecommerce', [AccessController::class,'home'])->middleware('role:Admin');

  Route::get('/clear-cache', function () {
    Artisan::call('cache:clear');
  });
  Route::get('/clear-view', function () {
    Artisan::call('view:clear');
  });
  Route::get('/clear-optimize', function () {
    Artisan::call('optimize:clear');
  });

app/Models/Calon.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;


/**
 * @mixin IdeHelperCalon
 */
class Calon extends Model
{
    public $table = 'calon';

  public $fillable = [
    'jenis_calon','nama_calon_1','nama_calon_2','status'
  ];

  public function calon(): BelongsTo
  {
    return $this->belongsTo(RefJenisCalon::class,'jenis_calon','id' );
  }

}

app/Http/Controllers/CalonController.php
<?php

  namespace App\Http\Controllers;

  use App\Models\Calon;
  use App\Models\RefJenisCalon;
  use App\Models\Tps;
  use App\Models\User;
  use Carbon\Carbon;
  use DB;
  use Exception;
  use Hash;
  use Illuminate\Contracts\Foundation\Application;
  use Illuminate\Contracts\View\Factory;
  use Illuminate\Http\RedirectResponse;
  use Illuminate\Http\Request;
  use Illuminate\Http\Response;
  use Illuminate\View\View;
  use Indonesia;
  use Yajra\DataTables\DataTables;

  class CalonController extends Controller
  {
    public array $data;
    public array $result;
    /**
     * @var Calon
     */
    protected Calon $calon;

    /**
     * Create a new controller instance.
     *
     * @param  Calon  $calon
     */
    public function __construct(Calon $calon)
    {
      $this->calon = $calon;
      $this->data = [];
      $this->result = [
        'results' => [],
      ];
      $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index()
    {
      $tgl = Carbon::now()->format('l, d F Y H:i');
      return view('pages.calon.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View
     */
    public function create()
    {
//      return view('pages.calon.create');
      return view('pages.calon.partial._form-add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request  $request
     * @return RedirectResponse
     */
    public function store(Request $request): RedirectResponse
    {
      $request->validate([
        'jenis_calon' => 'required',
        'nama_calon_1' => 'required',
        'nama_calon_2' => 'required',
      ]);

      $param = $request->all();

      $calon = new Calon();
      $calon->jenis_calon = $param['jenis_calon'];
      $calon->nama_calon_1 =  strtoupper($param['nama_calon_1']);
      $calon->nama_calon_2 = strtoupper($param['nama_calon_2']);
      $calon->status = 1;

      if ($calon->save()) {
        flash('Data Calon berhasil disimpan')->success();
        return back();
      }
      flash('Data Calon gagal disimpan')->success();
      return back()->withInput();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Application|Factory|Response|View|null
     */
    public function show(int $id)
    {
      //
      return view('',compact('id'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Application|Factory|Response|View
     */
    public function edit(int $id)
    {
      $id = $id ?? 0;
      $model = Calon::find($id);
      $jenisCalon = RefJenisCalon::find($model->jenis_calon);
      return view('pages.calon.partial._form-edit',compact('id','model','jenisCalon'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return RedirectResponse
     */
    public function update(Request $request, int $id): RedirectResponse
    {
      $request->validate([
        'prov_id' => 'required',
        'kota_id' => 'required',
        'kec_id' => 'required',
        'kel_id' => 'required',
        'nama_tps' => 'required',
        'email' => 'required',
        'password' => 'required',
      ]);

      $param = $request->all();

      $user = User::find($param['email']);
      $user->email = $param['email'];
      $user->name = strtolower(trim(Indonesia::findVillage($param['kel_id'])->name));
      $user->password = Hash::make($param['password']);
      $user->is_superadmin = 0;

      if ($user->save()) {
        $userSave = 1;
      } else {
        $userSave = 0;
      }

      $tps = Tps::find($id);
      $tps->prov_id = $param['prov_id'];
      $tps->kota_id = $param['kota_id'];
      $tps->kec_id = $param['kec_id'];
      $tps->kel_id = $param['kel_id'];
      $tps->user_id = $user->id;
      $tps->nama_tps = strtoupper($param['nama_tps']);
      $tps->status = 1;

      if ($userSave === 1 && $tps->save()) {
        flash('Data TPS berhasil disimpan')->success();
        return back();
      }
      flash('Data TPS gagal disimpan')->success();
      return back()->withInput();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return RedirectResponse
     * @throws Exception
     */
    public function destroy(int $id): RedirectResponse
    {
      if ($id) {
        $tps = Tps::find($id);
        if ($tps->delete()) {
          flash('Data tps berhasil dihapus', 'success');
          return back();
        }
        flash('Data tps berhasil dihapus', 'error');
        return back();
      }
      flash('ID Tidak ditemukan', 'error');
      return back();
    }

    public function getSelectJenisCalon(Request $request)
    {

      if ($request->ajax()) {
        $param = $request->except('type');
        $q = $request->has('q') ? $param['q'] : "";
        $jenis = RefJenisCalon::query()->where('jenis_calon','LIKE','%'.$q.'%')->get();
        foreach ($jenis as $item) {
          $this->result['results'][] = [
            'id' => $item->id,
            'text' => $item->jenis_calon,
          ];
        }
      }
      return response()->json($this->result);
    }

    public function getCalonData()
    {
      $query = DB::table('calon')
        ->select(['calon.id', 'ref_jenis_calon.jenis_calon', 'calon.nama_calon_1', 'calon.nama_calon_2', 'calon.status'])
        ->join('ref_jenis_calon', 'ref_jenis_calon.id','=','calon.jenis_calon')
        ->orderBy('calon.id', 'asc')
      ;

      return Datatables::of($query)
        ->addColumn('action', function ($calon) {
          $input['url'] = route('data-suara-calon.create',['id' => $calon->id]);
          $input['role'] = 'input_suara_calon';
          $edit['url'] = route('data-calon.edit', $calon->id);
          $edit['role'] = 'edit_data_calon';
          $delete['url'] = route('data-calon.destroy', $calon->id);
          $delete['role'] = 'hapus_calon';
          $format = 'd';

          return view('pages.calon.buttons', compact('input','edit', 'delete', 'format'));

        })
        ->editColumn('status', function ($calon) {
          if ($calon->status === 1) {
            $label = '<div class="badge badge-pill d-inline-flex align-items-center badge-glow badge-light-success mr-1 mb-1">Aktif</div>';
          } else {
            $label = '<div class="badge badge-pill d-inline-flex align-items-center badge-glow badge-light-danger mr-1 mb-1">Tidak Aktif</div>';
          }
          return $label;
        })
//            ->setRowClass('align-items-center')
        ->rawColumns(['status'])
        ->make(true);
    }
  }

resources/views/pages/calon/partial/_form-add.blade.php
<form class="form form-vertical" method="post" action="{{ route('data-calon.store') }}">
  @csrf
  <div class="modal-body" id="modal-body">
    <div class="form-group">
      <label for="select-jeniscalon-add">Jenis Calon</label>
      <div class="position-relative">
        <div class="form-group">
          <select name="jenis_calon" data-select2-id="select-jeniscalon-add" id="select-jeniscalon-add"
                  placeholder="Cari Jenis Calon" class="select2 selectJenisCalonAdd form-control @error('jenis_calon')
            is-invalid @enderror" required>
          </select>
{{--          <select class="form-control selectAddPaslon select2" id="select-paslon-add" name="paslon"></select>--}}
          @error('jenis_calon')
          <div class="invalid-feedback">
            <i class="bx bx-radio-circle"></i>
            {{ $message }}
          </div>
          @enderror
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6 col-12">
        <div class="form-group has-icon-left">
          <label for="nama-calon1">Nama Calon 1</label>
          <div class="position-relative">
            <input type="text" id="nama-calon1" class="form-control @error('nama_calon_1') is-invalid @enderror"
                   name="nama_calon_1" placeholder="Nama Calon 1" required>
            <div class="form-control-position">
              <i class="bx bx-user"></i>
            </div>
            @error('nama_calon_1')
            <div class="invalid-feedback">
              <i class="bx bx-radio-circle"></i>
              {{ $message }}
            </div>
            @enderror
          </div>
        </div>
      </div>
      <div class="col-md-6 col-12">
        <div class="form-group has-icon-left">
          <label for="nama-calon2">Nama Calon 2</label>
          <div class="position-relative">
            <input type="text" id="nama-calon2" class="form-control @error('nama_calon_2') is-invalid @enderror"
                   name="nama_calon_2" placeholder="Nama Calon 2" required>
            <div class="form-control-position">
              <i class="bx bx-user"></i>
            </div>
            @error('nama_calon_2')
            <div class="invalid-feedback">
              <i class="bx bx-radio-circle"></i>
              {{ $message }}
            </div>
            @enderror
          </div>
        </div>
      </div>
    </div>
    <div class="col-12 d-flex justify-content-end ">
      <button id="btnSubmit" type="submit" class="btn btn-primary mr-1 mb-1">Simpan</button>
{{--      <button id="btnReset" type="reset" class="btn btn-light-secondary mr-1 mb-1">Reset</button>--}}
    </div>
  </div>
</form>

resources/views/pages/calon/partial/_form-edit.blade.php
<form class="form form-vertical needs-validation" method="post" action="{{ route('data-calon.update', $id) }}" novalidate>
  @method('PUT')
  @csrf
  <div class="modal-body" id="modal-body">
    {!! Form::hidden('id',$id) !!}
    <div class="form-group">
      <label for="select-jeniscalon-edit">Jenis Calon</label>
      <div class="position-relative">
        <div class="form-group">
          <select name="jenis_calon" data-select2-id="select-jeniscalon-edit" id="select-jeniscalon-edit"
                  placeholder="Cari Jenis Calon" class="select2 selectJenisCalonEdit form-control @error('jenis_calon')
            is-invalid @enderror" required>
            <option value="{{ $jenisCalon->id }}">{{ $jenisCalon->jenis_calon}}</option>
          </select>
          {{--          <select class="form-control selectAddPaslon select2" id="select-paslon-add" name="paslon"></select>--}}
          @error('jenis_calon')
          <div class="invalid-feedback">
            <i class="bx bx-radio-circle"></i>
            {{ $message }}
          </div>
          @enderror
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6 col-12">
        <div class="form-group has-icon-left">
          <label for="nama-calon1">Nama Calon 1</label>
          <div class="position-relative">
            <input type="text" id="nama-calon1" class="form-control @error('nama_calon_1') is-invalid @enderror"
                   name="nama_calon_1" placeholder="Nama Calon 1" value="{{ $model->nama_calon_1 }}" required>
            <div class="form-control-position">
              <i class="bx bx-user"></i>
            </div>
            @error('nama_calon_1')
            <div class="invalid-feedback">
              <i class="bx bx-radio-circle"></i>
              {{ $message }}
            </div>
            @enderror
          </div>
        </div>
      </div>
      <div class="col-md-6 col-12">
        <div class="form-group has-icon-left">
          <label for="nama-calon2">Nama Calon 2</label>
          <div class="position-relative">
            <input type="text" id="nama-calon2" class="form-control @error('nama_calon_2') is-invalid @enderror"
                   name="nama_calon_2" placeholder="Nama Calon 2" value="{{ $model->nama_calon_2 }}" required>
            <div class="form-control-position">
              <i class="bx bx-user"></i>
            </div>
            @error('nama_calon_2')
            <div class="invalid-feedback">
              <i class="bx bx-radio-circle"></i>
              {{ $message }}
            </div>
            @enderror
          </div>
        </div>
      </div>
    </div>
    <div class="col-12 d-flex justify-content-end ">
      <button id="btnSubmit" type="submit" class="btn btn-primary mr-1 mb-1">Simpan</button>
{{--      <button id="btnReset" type="reset" class="btn btn-light-secondary mr-1 mb-1">Reset</button>--}}
    </div>
  </div>
</form>

resources/views/pages/calon/partial/_show.blade.php
<section>
  <div class="col-xl-4 col-md-12 whether-card">
    <div class="row">
      <!-- User Widget Starts -->
      <div class="col-xl-12 col-md-6 col-12 user-profile-card">
        <div class="card">
          <div class="card-header mx-auto pt-3">
            <div class="avatar bg-rgba-primary p-50">
              <img class="img-fluid" src="{{ asset('images/profile/user-uploads/social-2.jpg') }}" alt="img placeholder" height="150" width="150">
            </div>
          </div>
          <div class="card-content">
            <div class="card-body text-center">
              <h4>Maria Arnold</h4>
              <p>Developer</p>
              <!-- <p class="px-1">Jelly beans halvah cake chocolate gummies.</p> -->
              <div class="d-flex justify-content-around mb-1">
                <div class="card-icons d-flex flex-column">
                  <i class="bx bx-camera font-medium-5 font-weight-bold"></i>
                  <p>5693</p>
                </div>
                <div class="card-icons d-flex flex-column">
                  <i class="bx bx-heart font-medium-5 font-weight-bold"></i>
                  <p>856</p>
                </div>
                <div class="card-icons d-flex flex-column">
                  <i class="bx bx-user font-medium-5 font-weight-bold"></i>
                  <p>468</p>
                </div>
              </div>
              <button type="button" class="btn btn-primary glow px-4">Follow</button>
            </div>
          </div>
        </div>
      </div>
      <!-- User Widget Ends -->
    </div>
  </div>
</section>

resources/views/pages/calon/partial/scripts.blade.php
<script type="text/javascript">
  let tpl = '';

  function formatJenisCalon(result) {
    if (result.loading) return result.text;
    tpl = '<span><b>' + result.text + '</b></span><br><small>' + result.info + '</small>';
    return tpl;
  }

  function formatDefault(result) {
    if (!result.id) return result.text;
    tpl = $('<span><b>' + result.text + '</b></span>');
    return tpl;
  }

  function setTemplate(tipe) {
    let format = '';
    switch (tipe) {
      case 'jeniscalon':
        format = formatJenisCalon;
        break;
      default:
        format = formatDefault;
        break;
    }
    return format;
  }

  function renderSelect(selectInit, url, tpl, placehld) {
    return selectInit.select2({
      dropdownParent: $('#modal-form .modal-content'),
      dropdownAutoWidth: true,
      width: '100%',
      closeOnSelect: true,
      selectOnClose: false,
      allowClear: false,
      // minimumInputLength: 3,
      // maximumInputLength: 20,
      minimumResultsForSearch: 15,
      placeholder: placehld,
      ajax: {
        url: url,
        delay: 250,
        dataType: 'json',
        data: function (params) {
          let query = {
            q: params.term,
            i: selectInit.find(':selected').val(),
            type: 'public',
            page: params.page || 1
          };
          return query;
        },
        processResults: function (data, params) {
          params.page = params.page || 1;

          return {
            results: data.results,
            pagination: {
              more: (params.page * 15) < data.total_count
            }
          };
        },
        cache: true
      },
      escapeMarkup: function (markup) {
        return markup;
      },
      templateResult: tpl,
    });
  }

  /* Modal Show Global */
  $(document).ready(function () {
    $('body').on('click', '.modal-loader', function (e) {
      e.preventDefault();

      let me = $(this),
        url = me.data('url'),
        title = me.attr('title');

      $('#modalTitle').text(title);

      $.ajax({
        url: url,
        dataType: 'html',
        success: function (response) {
          $('#modal-fill').html(response);
          renderSelect($("#select-jeniscalon-add"), '{!! route('select.jeniscalon') !!}', setTemplate('jeniscalon'),'Pilih Jenis Calon');
          renderSelect($("#select-jeniscalon-edit"), '{!! route('select.jeniscalon') !!}', setTemplate('jeniscalon'),'Pilih Jenis Calon');
        },
      });

      $('#modal-form').modal('show');
    })
  });
  </script>