routes/web.php
<?php

use App\Http\Controllers\AccessController;
use App\Http\Controllers\CalonController;
use App\Http\Controllers\FrontController;
use App\Http\Controllers\HitungController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\LanguageController;
use App\Http\Controllers\SuaraCalonController;
use App\Http\Controllers\TpsController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\WilayahController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
  Route::get('/', [FrontController::class,'index'])->name('front');

  Auth::routes();

  // dashboard Routes
  Route::get('/home', [HomeController::class,'index'])->name('home');

  /*
   * Route Data Wilayah
   */
  Route::get('select-provinsi', [WilayahController::class,'getSelectProvinsi'])->name('select.prov');
  Route::get('select-kabupaten', [WilayahController::class,'getSelectKota'])->name('select.kota');
  Route::get('select-kecamatan', [WilayahController::class,'getSelectKecamatan'])->name('select.kecamatan');
  Route::get('select-kelurahan', [WilayahController::class,'getSelectDesa'])->name('select.desa');

  /*
   * Route Data TPS
   */
  Route::get('tps-list', [TpsController::class,'getTpsData'])->name('tps.list');
  Route::resource('data-tps', TpsController::class);

  //Route::view('tps', 'livewire.tps');
  Route::get('calon-list', [CalonController::class,'getCalonData'])->name('calon.list');
  Route::get('select-jeniscalon', [CalonController::class,'getSelectJenisCalon'])->name('select.jeniscalon');
  Route::resource('data-calon', CalonController::class);

  Route::get('input-suara-calon/{id}', 'SuaraCalonController@inputSuaraCalon')->name('suaracalon.input');
  Route::get('suaracalon-list', [SuaraCalonController::class,'getSuaraCalonData'])->name('suaracalon.list');
  Route::get('select-paslon', [SuaraCalonController::class,'getSelectPaslon'])->name('select.paslon');
  Route::get('select-tps', [SuaraCalonController::class,'getSelectTps'])->name('select.tps');
  Route::resource('data-suara-calon', SuaraCalonController::class);

  // Route Hitung Cepat
  Route::get('export', 'HitungController@export')->name('hitung.export');
  Route::get('hitung-suara', [HitungController::class,'getHitungSuaraData'])->name('hitungsuara.list');
  Route::resource('hitung-cepat', HitungController::class);

  //  Route::resource('/log-absen', 'LogController');

  Route::resource('pengguna', UserController::class);

  // locale Route
  Route::get('lang/{locale}', [LanguageController::class, 'swap']);

  // acess controller
  Route::get('/access-control',  [AccessController::class,'index']);
  Route::get('/access-control/{roles}', [AccessController::class,'roles']);
  Route::get('/ecommerce', [AccessController::class,'home'])->middleware('role:Admin');

  Route::get('/clear-cache', function () {
    Artisan::call('cache:clear');
  });
  Route::get('/clear-view', function () {
    Artisan::call('view:clear');
  });
  Route::get('/clear-optimize', function () {
    Artisan::call('optimize:clear');
  });

app/Models/HitungSuaraCalon.php
<?php

  namespace App\Models;

  use Illuminate\Database\Eloquent\Model;
  use Illuminate\Database\Eloquent\Relations\BelongsTo;
  use Illuminate\Database\Eloquent\Relations\HasOne;

  /**
 * @mixin IdeHelperHitungSuaraCalon
 */
  class HitungSuaraCalon extends Model
  {
    /**
     * @var string
     */
    public $table = 'hitung_suara_calon';

    /**
     * @var string
     */
//    protected $data = '';

    public $fillable = [
      'kecamatan', 'desa','suara1', 'suara2', 'suara_tidak_sah', 'no_tps','dpt', 'status'
    ];

    protected $casts = [

    ];

    public function calon(): HasOne
    {
      return $this->hasOne(Calon::class, 'id', 'calon_id');
    }

    public function tps(): HasOne
    {
      return $this->hasOne(Tps::class, 'id', 'tps_id');
    }

    public function kecamatan(): BelongsTo
    {
      return $this->belongsTo(Kecamatan::class, 'id', 'kecamatan');
    }

    public function scopeTpsMasuk($query)
    {
      return $query->where('status', 1);
    }

    public function scopeTpsBlmMasuk($query)
    {
      return $query->where('status', 0);
    }

    public function scopeStatus($query, $status)
    {
      return $query->where('status', $status);
    }

    public static function countTps($kecid): int
    {
      $kecid = $kecid ?? null;
      if (null !== $kecid) {
        $tps = self::where('kecamatan', $kecid)->get();
        return (null !== $tps) ? $tps->count() : 0;
      }
      return 0;
    }
  }

resources/views/pages/hitung-suara-calon/_form.blade.php
@if($form === 'add')
  <form class="form form-vertical needs-validation" method="post" action="{{ route('data-suara-calon.store') }}" novalidate>
    @csrf
    <div class="modal-body" id="modal-body">
      <div class="row">
        <div class="col-12">
          {{--        {!! Form::hidden('id',$model->id) !!}--}}
          <div class="form-group">
            <label for="select-provinsi">Pasangan Calon</label>
            <div class="position-relative">
              <div class="form-group">
                {!! Form::select('paslon', $jenisCalon, [],['class' => 'form-control selectPaslon select2', 'id'=>'select-paslon']) !!}
                @error('paslon')
                <div class="invalid-feedback">
                  <i class="bx bx-radio-circle"></i>
                  {{ $message }}
                </div>
                @enderror
              </div>
            </div>
          </div>
          <div class="form-group">
            <label for="select-tps">TPS</label>
            <div class="position-relative">
              <div class="form-group">
                {!! Form::select('tps', $tps, $id,['class' => 'form-control selectTps select2','id'=>'select-tps']) !!}
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6 col-12">
              <div class="form-group has-icon-left">
                <label for="jumlah-suara">Jumlah Suara Calon</label>
                <div class="position-relative">
                  <input type="text" id="jumlah-suara" class="form-control @error('jumlah_suara') is-invalid @enderror"
                         name="jumlah_suara" placeholder="Jumlah Suara Calon" required>
                  <div class="form-control-position">
                    <i class="bx bx-calculator"></i>
                  </div>
                  @error('jumlah_suara')
                  <div class="invalid-feedback">
                    <i class="bx bx-radio-circle"></i>
                    {{ $message }}
                  </div>
                  @enderror
                </div>
              </div>
            </div>
          </div>
          <div class="col-12 d-flex justify-content-end ">
            <button id="btnSubmit" type="submit" class="btn btn-primary mr-1 mb-1">Simpan</button>
            <button id="btnReset" type="reset" class="btn btn-light-secondary mr-1 mb-1">Reset</button>
          </div>
        </div>
      </div>
    </div>
  </form>
@else
  <form class="form form-vertical needs-validation" method="post" action="{{ route('data-suara-calon.update', $id) }}" novalidate>
    @method('PUT')
    @csrf
    <div class="modal-body" id="modal-body">
      <div class="row">
        <div class="col-12">
          {!! Form::hidden('id',$model->id) !!}
          <div class="form-group">
            <label for="select-provinsi">Pasangan Calon</label>
            <div class="position-relative">
              <div class="form-group">
                {!! Form::select('paslon', $jenisCalon, $calon->jenis_calon,['class' => 'form-control selectPaslon select2',
                'id'=>'select-paslon'])
                 !!}
              </div>
            </div>
          </div>
          <div class="form-group">
            <label for="select-tps">TPS</label>
            <div class="position-relative">
              <div class="form-group">
                {!! Form::select('tps', $tps, $tpss->id,['class' => 'form-control selectTps select2','id'=>'select-tps']) !!}
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6 col-12">
              <div class="form-group has-icon-left">
                <label for="jumlah-suara">Jumlah Suara Calon</label>
                <div class="position-relative">
                  <input type="text" id="jumlah-suara" class="form-control @error('jumlah_suara') is-invalid @enderror"
                         name="jumlah_suara" value="{{ $model->jumlah_suara }}" placeholder="Jumlah Suara Calon" required>
                  <div class="form-control-position">
                    <i class="bx bx-calculator"></i>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-12 d-flex justify-content-end ">
            <button id="btnSubmit" type="submit" class="btn btn-primary mr-1 mb-1">Simpan</button>
            <button id="btnReset" type="reset" class="btn btn-light-secondary mr-1 mb-1">Reset</button>
          </div>
        </div>
      </div>
    </div>
  </form>
@endif

resources/views/pages/hitung-suara-calon/_index.blade.php
@extends('layouts.contentLayoutMaster')
{{-- title --}}
@section('title','Hitung Cepat')

{{-- vendor style --}}
@section('vendor-styles')
  {{--  <link rel="stylesheet" type="text/css" href="{{asset('vendors/css/tables/datatable/datatables.min.css')}}">--}}
  <link rel="stylesheet" type="text/css" href="{{asset('css/pages/dashboard-analytics.css')}}">
  <link rel="stylesheet" type="text/css" href="{{asset('css/pages/hitung-cepat.min.css')}}">
@endsection
{{-- page-styles --}}

@section('content')
  <section>
    @include('flash::message')
    @include('widgets.error')
  </section>
  <section>
    {{--    @include('widgets.filter-hitung')--}}
    {{--    @livewire('hitung')--}}
  </section>

  <!-- Zero configuration table -->
  <section id="basic-datatable" class="invoice-list-wrapper">
    <!-- create invoice button-->
    <div class="invoice-create-btn mb-1">
      <button type="button" id="btnTambah" class="btn btn-primary glow invoice-create modal-loader" aria-pressed="true" data-toggle="modal"
              data-target="#modal-form" data-url="{{ route('hitung-cepat.create') }}" title="TAMBAH DATA HITUNG SUARA">
        <i class="bx bx-plus-circle"></i>
        Tambah
      </button>
      {{--      <a href="app-invoice-add.html" class="btn btn-primary glow invoice-create" role="button" aria-pressed="true">--}}
      {{--        Tambah Hitung</a>--}}
    </div>
    <!-- Options and filter dropdown button-->
    @include('widgets.filter-hitung')
    <div class="table-responsive">
      <table id="table-hitungcepat" class="table table-hover invoice-data-table dt-responsive nowrap" style="width:100%">
        <thead>
        <tr class="text-center">
          <th width="3%"></th>
          {{--          <th width="3%">No</th>--}}
          <th>Kecamatan</th>
          <th>Kelurahan</th>
          <th>TPS</th>
          <th>Suara Calon 1</th>
          <th>Suara Calon 2</th>
          <th>Suara Tidak Sah</th>
          <th width="3%">Aksi</th>
        </tr>
        </thead>
      </table>
    </div>
    {{--    <div class="row">--}}
    {{--      <div class="col-12">--}}
    {{--        <div class="card">--}}
    {{--          <div class="card-header">--}}
    {{--            <!-- head -->--}}
    {{--            <h5 class="card-title">PERHITUNGAN SUARA CEPAT PASANGAN CALON (PASLON)</h5>--}}
    {{--            <!-- Single Date Picker and button -->--}}
    {{--            <div class="heading-elements">--}}
    {{--              <ul class="list-inline mb-0">--}}
    {{--                <li class="ml-2">--}}
    {{--                  <a href="{{ route('hitung.export') }}" class="btn btn-danger">--}}
    {{--                    <i class="bx bx-export"></i>--}}
    {{--                    Eksport--}}
    {{--                  </a>--}}
    {{--                  <button type="button" id="btnTambah" class="btn btn-primary modal-loader" data-toggle="modal"--}}
    {{--                          data-target="#modal-form" data-url="{{ route('hitung-cepat.create') }}" title="TAMBAH DATA HITUNG SUARA">--}}
    {{--                    <i class="bx bx-plus-circle"></i>--}}
    {{--                    Tambah--}}
    {{--                  </button>--}}
    {{--                </li>--}}
    {{--              </ul>--}}
    {{--            </div>--}}
    {{--          </div>--}}
    {{--          <div class="card-content">--}}
    {{--            <div class="card-body m-0">--}}
    {{--              <div class="table-responsive">--}}
    {{--                <table id="table-hitungcepat" class="table table-hover table-responsive">--}}
    {{--                  <thead class="thead-light">--}}
    {{--                  <tr class="text-center">--}}
    {{--                    <th width="3%">No</th>--}}
    {{--                    <th>Kecamatan</th>--}}
    {{--                    <th>Kelurahan</th>--}}
    {{--                    <th>TPS</th>--}}
    {{--                    <th>Suara Calon 1</th>--}}
    {{--                    <th>Suara Calon 2</th>--}}
    {{--                    <th>Suara Tidak Sah</th>--}}
    {{--                    <th width="3%">Aksi</th>--}}
    {{--                  </tr>--}}
    {{--                  </thead>--}}
    {{--                </table>--}}
    {{--                            </div>--}}
    {{--            </div>--}}
    {{--          </div>--}}
    {{--        </div>--}}
    {{--      </div>--}}
    {{--    </div>--}}
    @include('widgets.modal')
  </section>
@endsection
{{-- vendor scripts --}}
@section('vendor-scripts')
  <script src="{{asset('vendors/js/tables/datatable/datatables.min.js')}}"></script>
  <script src="{{asset('vendors/js/tables/datatable/dataTables.bootstrap4.min.js')}}"></script>
  {{--    <script src="{{asset('vendors/js/tables/datatable/dataTables.checkboxes.min.js')}}"></script>--}}
  {{--  <script src="{{asset('vendors/js/tables/datatable/dataTables.select.min.js')}}"></script>--}}
  {{--  <script src="{{asset('vendors/js/tables/jszip/dist/jszip.min.js')}}"></script>--}}
  {{--  <script src="{{asset('vendors/js/tables/datatable/dataTables.responsive.min.js')}}"></script>--}}
  {{--  <script src="{{asset('vendors/js/tables/datatable/dataTables.buttons.min.js')}}"></script>--}}
  {{--  <script src="{{asset('vendors/js/tables/datatable/buttons.html5.min.js')}}"></script>--}}
  {{--  <script src="{{asset('vendors/js/tables/datatable/buttons.print.min.js')}}"></script>--}}
  {{--  <script src="{{asset('vendors/js/tables/datatable/buttons.bootstrap.min.js')}}"></script>--}}
  {{--  <script src="{{asset('vendors/js/tables/datatable/pdfmake.min.js')}}"></script>--}}
  {{--  <script src="{{asset('vendors/js/tables/datatable/vfs_fonts.js')}}"></script>--}}
@endsection
{{-- page scripts --}}
@section('page-scripts')
  {{--  <script src="{{asset('app-assets/js/scripts/pages/app-invoice.js')}}"></script>--}}
  <script>
    $(function () {
      if ($(".invoice-data-table").length) {
        let dataListView = $(".invoice-data-table").DataTable({
          processing: true,
          serverSide: true,
          ajax: {
            url: '{!! route('hitungsuara.list') !!}'
          },
          columns: [
            // {data: '', name: '', searchable: false,orderable: false},
            // {data: '', name: '', searchable: false,orderable: false},
            {data: 'id', name: 'id'},
            // {data: 'kecamatan', name: 'kecamatan'},
            {data: 'nama_kecamatan', name: 'indonesia_districts.name'},
            // {data: 'desa', name: 'desa'},
            {data: 'nama_desa', name: 'indonesia_villages.name'},
            {data: 'no_tps', name: 'no_tps'},
            // {data: 'nama_calon1', name: 'nama_calon1'},
            // {data: 'nama_calon2', name: 'nama_calon2'},
            {data: 'suara1', name: 'suara1'},
            {data: 'suara2', name: 'suara2'},
            {data: 'suara_tidak_sah', name: 'suara_tidak_sah'},
            {data: 'action', name: 'action', searchable: false, orderable: false}
          ],
          columnDefs: [
            {
              targets: 0,
              className: "control"
            },
            {
              orderable: true,
              targets: 0,
              checkboxes: {selectRow: true}
            },
            {
              targets: [0, 1],
              orderable: false
            },
          ],
          order: [1, 'asc'],
          dom:
            '<"top d-flex flex-wrap"<"action-filters flex-grow-1"f><"actions action-btns d-flex align-items-center">><"clear">rt<"bottom"p>',
          language: {
            search: "",
            searchPlaceholder: "Cari Data.."
          },
          select: {
            style: "multi",
            selector: "td:first-child",
            items: "row"
          },
          responsive: {
            details: {
              type: "column",
              target: 0
            }
          }
        });
      }
      // To append actions dropdown inside action-btn div
      var invoiceFilterAction = $(".invoice-filter-action");
      var invoiceOptions = $(".invoice-options");
      $(".action-btns").append(invoiceFilterAction, invoiceOptions);

      // add class in row if checkbox checked
      $(".dt-checkboxes-cell")
        .find("input")
        .on("change", function () {
          let $this = $(this);
          if ($this.is(":checked")) {
            $this.closest("tr").addClass("selected-row-bg");
          } else {
            $this.closest("tr").removeClass("selected-row-bg");
          }
        });
      // Select all checkbox
      $(document).on("change", ".dt-checkboxes-select-all input", function () {
        if ($(this).is(":checked")) {
          $(".dt-checkboxes-cell")
            .find("input")
            .prop("checked", this.checked)
            .closest("tr")
            .addClass("selected-row-bg");
        } else {
          $(".dt-checkboxes-cell")
            .find("input")
            .prop("checked", "")
            .closest("tr")
            .removeClass("selected-row-bg");
        }
      });

      // ********Invoice Edit***********//
      // --------------------------------
      // form repeater jquery
      if ($(".invoice-item-repeater").length) {
        $(".invoice-item-repeater").repeater({
          show: function () {
            $(this).slideDown();
          },
          hide: function (deleteElement) {
            $(this).slideUp(deleteElement);
          }
        });
      }
      // dropdown form's prevent parent action
      $(document).on("click", ".invoice-tax", function (e) {
        e.stopPropagation();
      });
      $(document).on("click", ".invoice-apply-btn", function () {
        var $this = $(this);
        var discount = $this
          .closest(".dropdown-menu")
          .find("#discount")
          .val();
        var tax1 = $this
          .closest(".dropdown-menu")
          .find("#Tax1 option:selected")
          .text();
        var tax2 = $this
          .closest(".dropdown-menu")
          .find("#Tax2 option:selected")
          .text();
        $this
          .parents()
          .eq(4)
          .find(".discount-value")
          .html(discount + "%");
        $this
          .parents()
          .eq(4)
          .find(".tax1")
          .html(tax1);
        $this
          .parents()
          .eq(4)
          .find(".tax2")
          .html(tax2);
      });
      // // on product change also change product description
      $(document).on("change", ".invoice-item-select", function (e) {
        var selectOption = this.options[e.target.selectedIndex].text;
        // switch case for product select change also change product description
        switch (selectOption) {
          case "Frest Admin Template":
            $(e.target)
              .closest(".invoice-item-filed")
              .find(".invoice-item-desc")
              .val("The most developer friendly & highly customisable HTML5 Admin");
            break;
          case "Stack Admin Template":
            $(e.target)
              .closest(".invoice-item-filed")
              .find(".invoice-item-desc")
              .val("Ultimate Bootstrap 4 Admin Template for Next Generation Applications.");
            break;
          case "Robust Admin Template":
            $(e.target)
              .closest(".invoice-item-filed")
              .find(".invoice-item-desc")
              .val(
                "Robust admin is super flexible, powerful, clean & modern responsive bootstrap admin template with unlimited possibilities"
              );
            break;
          case "Apex Admin Template":
            $(e.target)
              .closest(".invoice-item-filed")
              .find(".invoice-item-desc")
              .val("Developer friendly and highly customizable Angular 7+ jQuery Free Bootstrap 4 gradient ui admin template. ");
            break;
          case "Modern Admin Template":
            $(e.target)
              .closest(".invoice-item-filed")
              .find(".invoice-item-desc")
              .val("The most complete & feature packed bootstrap 4 admin template of 2019!");
            break;
        }
      });
      // print button
      if ($(".invoice-print").length > 0) {
        $(".invoice-print").on("click", function () {
          window.print();
        })
      }
      {{--let tabelHitung = $('#table-hitungcepat').DataTable({--}}
      {{--  // dom: 'Bfrtip',--}}
      {{--  processing: true,--}}
      {{--  serverSide: true,--}}
      {{--  ajax: {--}}
      {{--    url: '{!! route('hitungsuara.list') !!}'--}}
      {{--  },--}}
      {{--  columns: [--}}
      {{--    {data: 'id', name: 'id'},--}}
      {{--    // {data: 'kecamatan', name: 'kecamatan'},--}}
      {{--    {data: 'nama_kecamatan', name: 'indonesia_districts.name'},--}}
      {{--    // {data: 'desa', name: 'desa'},--}}
      {{--    {data: 'nama_desa', name: 'indonesia_villages.name'},--}}
      {{--    {data: 'no_tps', name: 'no_tps'},--}}
      {{--    // {data: 'nama_calon1', name: 'nama_calon1'},--}}
      {{--    // {data: 'nama_calon2', name: 'nama_calon2'},--}}
      {{--    {data: 'suara1', name: 'suara1'},--}}
      {{--    {data: 'suara2', name: 'suara2'},--}}
      {{--    {data: 'suara_tidak_sah', name: 'suara_tidak_sah'},--}}
      {{--    {data: 'action', name: 'action', searchable: false, orderable: false}--}}
      {{--  ],--}}
      {{--});--}}

      // Clear Form Value
      $("#btnReset").click(function () {
        let forms = document.getElementsByClassName('needs-validation');
        let validation = Array.prototype.filter.call(forms, function (form) {
          form.addEventListener('reset', function (event) {
            form.classList.val('');
          }, false);
        });
        $('.select2').val('').trigger('change');
      })
    });
  </script>
@endsection

resources/views/pages/hitung-suara-calon/edit.blade.php
@extends('layouts.contentLayoutMaster')
{{-- title --}}
@section('title','Datatables')

{{-- vendor style --}}
@section('vendor-styles')
  <link rel="stylesheet" type="text/css" href="{{ asset('vendors/css/forms/select/select2.min.css')}}">
@endsection
{{-- page-styles --}}

@section('content')
  <div class="row">
    <div class="col-12">

    </div>
  </div>
  <!-- Zero configuration table -->
  <section id="add-tps">
    <a href="{{ route('data-calon.index') }}" class="btn btn-link mr-1 mb-1"><i class="bx bx-arrow-back"></i> Kembali</a>
    <div class="row match-height">
      <div class="col-9">
        <div class="card">
          <div class="card-header">
            <h4 class="card-title">TAMBAH CALON</h4>
          </div>
          <div class="card-content">
            <div class="card-body">
              <form class="form form-horizontal needs-validation" method="post" action="{{route('data-calon.store') }}" novalidate>
                @csrf
                <div class="form-body">
                  <div class="row">
                    <div class="col-md-4 text-right">
                      <label for="select-provinsi">Jenis Calon</label>
                    </div>
                    <div id="sel-jenis" class="col-md-8 form-group ">
                      <div class="position-relative">
                        <div class="form-group">
                          <select name="jenis_calon" data-select2-id="select-jeniscalon" id="select-jeniscalon"
                                  placeholder="Cari Jenis Calon" class="select2 form-control @error('jenis_calon')
                            is-invalid @enderror" required>
                          </select>
                          {{--                                                    <div class="valid-feedback">Example valid custom select feedback</div>--}}
                          {{--                                                    <div class="invalid-feedback">--}}
                          {{--                                                        Please Select the field--}}
                          {{--                                                    </div>--}}
                          @error('jenis_calon')
                          <div class="invalid-feedback">
                            <i class="bx bx-radio-circle"></i>
                            {{ $message }}
                          </div>
                          @enderror
                        </div>
                      </div>
                    </div>
                    <div class="col-md-4 text-right">
                      <label>Nama Calon 1</label>
                    </div>
                    <div class="col-md-8 form-group">
                      <div class="position-relative has-icon-left">
                        <input type="text" id="nama-calon1" class="form-control @error('nama_calon_1') is-invalid @enderror"
                               name="nama_calon_1" placeholder="Nama Calon 1" required>
                        <div class="form-control-position">
                          <i class="bx bx-box"></i>
                        </div>
                        @error('nama_calon_1')
                        <div class="invalid-feedback">
                          <i class="bx bx-radio-circle"></i>
                          {{ $message }}
                        </div>
                        @enderror
                      </div>
                    </div>
                    <div class="col-md-4 text-right">
                      <label for="nama-calon2">Nama Calon 2</label>
                    </div>
                    <div class="col-md-8 form-group">
                      <div class="position-relative has-icon-left">
                        <input type="text" id="nama-calon2" class="form-control @error('nama_calon_2') is-invalid @enderror"
                               name="nama_calon_2" placeholder="Nama Calon 2" required>
                        <div class="form-control-position">
                          <i class="bx bx-box"></i>
                        </div>
                        @error('nama_calon_2')
                        <div class="invalid-feedback">
                          <i class="bx bx-radio-circle"></i>
                          {{ $message }}
                        </div>
                        @enderror
                      </div>
                    </div>
                    <div class="col-12 d-flex justify-content-end ">
                      <button id="btnSubmit" type="submit" class="btn btn-primary mr-1 mb-1">Simpan</button>
                      <button id="btnReset" type="reset" class="btn btn-light-secondary mr-1 mb-1">Reset</button>
                    </div>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!--/ Zero configuration table -->

@endsection
{{-- vendor scripts --}}
@section('vendor-scripts')
  <script src="{{asset('vendors/js/forms/select/select2.full.min.js')}}"></script>
  <script src="{{asset('js/scripts/forms/select/form-select2.js')}}"></script>
@endsection
{{-- page scripts --}}
{{--    <script src="{{asset('js/scripts/forms/form-tooltip-valid.js')}}"></script>--}}
@section('page-scripts')
  <script>
    $(function () {
      // Clear Form Value
      $("#btnReset").click(function () {
        let forms = document.getElementsByClassName('needs-validation');
        let validation = Array.prototype.filter.call(forms, function (form) {
          form.addEventListener('reset', function (event) {
            form.classList.val('');
          }, false);
        });
        $('.select2').val('').trigger('change');
      })

      let selectJenisCalon = $("#select-jeniscalon");

      selectJenisCalon.select2({
        dropdownAutoWidth: true,
        width: '100%',
        closeOnSelect: true,
        selectOnClose: false,
        allowClear: false,
        ajax: {
          url: "{!! route('select.jeniscalon') !!}",
          dataType: 'json',
          delay: 250,
          data: function (params) {
            let query = {
              q: params.term, // search term
              type: 'public',
              page: params.page || 1
            };
            return query;
          },
          processResults: function (data, params) {
            params.page = params.page || 1;

            return {
              results: data.results,
              pagination: {
                more: (params.page * 15) < data.total_count
              }
            };
          },
          cache: true
        },
        placeholder: 'Cari Jenis Salon',
        escapeMarkup: function (markup) {
          return markup;
        }, // let our custom formatter work
        //minimumInputLength: 1,
        minimumResultsForSearch: 15,
        templateResult: formatJenisCalon,
      });

      function formatJenisCalon(result) {
        if (result.loading) return result.text;
        let tpl = '<span><b>' + result.text + '</b></span>';
        return tpl;
      }
    });
  </script>
@endsection