routes/web.php
<?php

use App\Http\Controllers\AccessController;
use App\Http\Controllers\CalonController;
use App\Http\Controllers\FrontController;
use App\Http\Controllers\HitungController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\LanguageController;
use App\Http\Controllers\SuaraCalonController;
use App\Http\Controllers\TpsController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\WilayahController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
  Route::get('/', [FrontController::class,'index'])->name('front');

  Auth::routes();

  // dashboard Routes
  Route::get('/home', [HomeController::class,'index'])->name('home');

  /*
   * Route Data Wilayah
   */
  Route::get('select-provinsi', [WilayahController::class,'getSelectProvinsi'])->name('select.prov');
  Route::get('select-kabupaten', [WilayahController::class,'getSelectKota'])->name('select.kota');
  Route::get('select-kecamatan', [WilayahController::class,'getSelectKecamatan'])->name('select.kecamatan');
  Route::get('select-kelurahan', [WilayahController::class,'getSelectDesa'])->name('select.desa');

  /*
   * Route Data TPS
   */
  Route::get('tps-list', [TpsController::class,'getTpsData'])->name('tps.list');
  Route::resource('data-tps', TpsController::class);

  //Route::view('tps', 'livewire.tps');
  Route::get('calon-list', [CalonController::class,'getCalonData'])->name('calon.list');
  Route::get('select-jeniscalon', [CalonController::class,'getSelectJenisCalon'])->name('select.jeniscalon');
  Route::resource('data-calon', CalonController::class);

  Route::get('input-suara-calon/{id}', 'SuaraCalonController@inputSuaraCalon')->name('suaracalon.input');
  Route::get('suaracalon-list', [SuaraCalonController::class,'getSuaraCalonData'])->name('suaracalon.list');
  Route::get('select-paslon', [SuaraCalonController::class,'getSelectPaslon'])->name('select.paslon');
  Route::get('select-tps', [SuaraCalonController::class,'getSelectTps'])->name('select.tps');
  Route::resource('data-suara-calon', SuaraCalonController::class);

  // Route Hitung Cepat
  Route::get('export', 'HitungController@export')->name('hitung.export');
  Route::get('hitung-suara', [HitungController::class,'getHitungSuaraData'])->name('hitungsuara.list');
  Route::resource('hitung-cepat', HitungController::class);

  //  Route::resource('/log-absen', 'LogController');

  Route::resource('pengguna', UserController::class);

  // locale Route
  Route::get('lang/{locale}', [LanguageController::class, 'swap']);

  // acess controller
  Route::get('/access-control',  [AccessController::class,'index']);
  Route::get('/access-control/{roles}', [AccessController::class,'roles']);
  Route::get('/ecommerce', [AccessController::class,'home'])->middleware('role:Admin');

  Route::get('/clear-cache', function () {
    Artisan::call('cache:clear');
  });
  Route::get('/clear-view', function () {
    Artisan::call('view:clear');
  });
  Route::get('/clear-optimize', function () {
    Artisan::call('optimize:clear');
  });

app/Models/HitungCepat.php
<?php

  namespace App\Models;

  use Illuminate\Database\Eloquent\Model;
  use Illuminate\Database\Eloquent\Relations\BelongsTo;
  use Illuminate\Database\Eloquent\Relations\HasOne;

  /**
 * @mixin IdeHelperHitungCepat
 */
  class HitungCepat extends Model
  {
    /**
     * @var string
     */
    public $table = 'hitung_suara';

    /**
     * @var string
     */
//    protected $data = '';

    public $fillable = [
      'kabupaten','kecamatan', 'desa', 'calon1_id', 'calon2_id', 'nama_calon1', 'nama_calon2', 'suara1', 'suara2', 'suara_tidak_sah', 'no_tps', 'status','dpt'
    ];

    protected $attributes = [
        'kabupaten' => '7312'
    ];

    protected $casts = [
        'status' => 'bool',
    ];

    public function calon(): HasOne
    {
      return $this->hasOne(Calon::class, 'id', 'calon_id');
    }

    public function tps(): HasOne
    {
      return $this->hasOne(Tps::class, 'id', 'tps_id');
    }

      public function kabupaten(): BelongsTo
      {
          return $this->belongsTo(Kota::class, 'kabupaten', 'code');
      }

    public function kec(): BelongsTo
    {
      return $this->belongsTo(Kecamatan::class, 'kecamatan', 'code');
    }

    public function desa(): BelongsTo
    {
      return $this->belongsTo(Kelurahan::class, 'desa', 'code');
    }

    public function scopeTpsMasuk($query)
    {
      return $query->where('status', 1);
    }

    public function scopeTpsBlmMasuk($query)
    {
      return $query->where('status', 0);
    }

    public function scopeStatus($query, $status)
    {
      return $query->where('status', $status);
    }

    public static function getJumlahSuara($id)
    {
      $id = $id ?? null;
      if (null !== $id) {
        $jumlah = self::find($id);
        return (null !== $jumlah) ? $jumlah->jumlah_suara_1 + $jumlah->jumlah_suara_2 : 0;
      }
      return 0;
    }

    public static function getTotalSuara($id)
    {
      $id = $id ?? null;
      if (null !== $id) {
        $total = self::find($id);
        return (null !== $total) ? $total->total_suara : 0;
      }
      return 0;
    }

    public static function getPersentaseSuara($id)
    {
      $id = $id ?? null;
      if (null !== $id) {
        $persen = self::find($id);
        return (null !== $persen) ? $persen->persentase_suara : 0;
      }
      return 0;
    }

    public static function countTps($tpsId): int
    {
      $tpsId = $tpsId ?? null;
      if (null !== $tpsId) {
        $tps = self::where('tps_id', $tpsId)->get();
        return (null !== $tps) ? $tps->count() : 0;
      }
      return 0;
    }
  }

app/Http/Livewire/Pilkada/HitungCepat.php
<?php

namespace App\Http\Livewire\Pilkada;

use Livewire\Component;
use App\Models\HitungCepat as ModelHitung;

class HitungCepat extends Component
{
    public ModelHitung $hitung;

    /** @var int */
    public int $totalSuara1 = 0;

    /** @var int */
    public int $totalSuara2 = 0;

    /** @var int */
    public int $totalSuaraSah = 0;

    /** @var int */
    public int $totalSuaraTidakSah = 0;

    /** @var int */
    public int $totalDpt = 0;

    /** @var int */
    public int $refreshInSeconds = 60;

    public float $persenSuara1 = 0;
    public float $persenSuara2 = 0;
    public float $persenSuara = 0;
    public float $persenSuaraTidakSah = 0;
    public float $persenSuaraSah = 0;
    public int $partisipan = 0;
    public int $totalTps = 0;
    public float $persenPartisipan = 0;
    public int $suaraMasuk = 0;
    public int $suaraBlmMasuk = 0;
    public int $totalSuaraMasuk = 0;
    public float $persentaseSuaraMasuk = 0;
    public float $persentaseSuaraBlmMasuk = 0;
    public float $persentaseSuaraAll = 0;

    public function mount(ModelHitung $hitung, int $refreshInSeconds = 60): void
    {
        $this->hitung = $hitung;
        $this->totalTps = config('global.total_tps', 517);
        $this->totalDpt = config('global.total_dpt', 175415);
        $query = $this->hitung->query();

        $tpsMasuk = $query->status(1)->get();
        $tpsBlmMasuk = $query->status(0)->get();

        $this->persentaseSuaraMasuk = ($tpsMasuk->count() / $this->totalTps) * 100;
        $this->persentaseSuaraBlmMasuk = (($this->totalTps - $tpsBlmMasuk->count()) / $this->totalTps) * 100;
        $this->persentaseSuaraAll = (($this->persentaseSuaraMasuk + $this->persentaseSuaraBlmMasuk) / $this->totalTps) * 100;

        $this->hitung->get()->each(function ($item) {
            $this->totalSuara1 += $item->suara1;
            $this->totalSuara2 += $item->suara2;
            $this->totalSuaraTidakSah += $item->suara_tidak_sah;
            $this->totalSuaraSah = $this->totalSuara1 + $this->totalSuara2;
            $this->persenSuara1 = (float) ($this->totalSuara1 / $this->totalSuaraSah) * 100;
            $this->persenSuara2 = (float) ($this->totalSuara2 / $this->totalSuaraSah) * 100;
            $this->persenSuaraSah = (float) ($this->totalSuaraSah / $this->totalDpt) * 100;
            $this->persenSuaraTidakSah = (float) ($this->totalSuaraTidakSah / $this->totalDpt) * 100;
            $this->suaraMasuk = $this->totalSuaraSah + $this->totalSuaraTidakSah;
            $this->suaraBlmMasuk = $this->totalDpt - $this->suaraMasuk;
            $this->partisipan = $this->suaraMasuk;
            $this->persenSuara = (float) (($this->suaraMasuk + $this->suaraBlmMasuk) / $this->totalDpt) * 100;
        });

        $this->refreshInSeconds = $refreshInSeconds;
        $this->emit('chartUpdate');
    }

    public function render()
    {
        return view('livewire.pilkada.hitung-cepat', [
            'refreshInSeconds' => config('global.refresh_interval_in_seconds', 60),
        ]);
    }
}

resources/views/pages/hitung-cepat/partial/_form-add.blade.php
<form class="form form-vertical" method="POST" action="{{ route('hitung-cepat.store') }}">
  @csrf
  <div class="modal-body" id="modal-body">
    <div class="row">
      <div class="col-md-5 col-12">
        <div class="form-group">
          <label for="select-kecamatan-add">Kecamatan</label>
          <div class="position-relative">
            <div class="form-group">
              <select class="form-control selectKecAdd select2" id="select-kecamatan-add" name="kecamatan"></select>
              @error('kecamatan')
              <div class="invalid-feedback">
                <i class="bx bx-radio-circle"></i>
                {{ $message }}
              </div>
              @enderror
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-4 col-12">
        <div class="form-group">
          <label for="select-desa-add">Kelurahan</label>
          <div class="position-relative">
            <div class="form-group">
              <select class="form-control selectDesaAdd select2" id="select-desa-add" name="desa"></select>
              @error('desa')
              <div class="invalid-feedback">
                <i class="bx bx-radio-circle"></i>
                {{ $message }}
              </div>
              @enderror
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="form-group">
          <label for="tps-add">TPS</label>
          <div class="position-relative">
            <div class="form-group">
              {!! Form::number('tps','',['class' => 'form-control','id' =>'tps-add','placeholder' => 'TPS']) !!}
              <div class="form-control-position">
                <i class="bx bx-building"></i>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-9">
        <div class="form-group">
          <label for="calon-add">Nama Pasangan Calon</label>
          <div class="position-relative">
            <div class="form-group">
              {!! Form::hidden('calon1_id',$calon[0]['id']) !!}
              {!! Form::text('nama_calon1',$calon[0]['id'].'. '.$calon[0]['nama_calon_1'] .' - '. $calon[0]['nama_calon_2'],['class' =>
              'form-control','id'=>'calon-add','placeholder' => 'Suara','readonly']) !!}
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="form-group">
          <label for="tps-add">Jumlah Suara</label>
          <div class="position-relative">
            <div class="form-group">
              {!! Form::number('suara1',old('suara1') ?? '',['class' => 'form-control','id' =>'suara'.$calon[0]['id'],'placeholder' =>
              'Suara']) !!}
              <div class="form-control-position">
                <i class="bx bx-calculator"></i>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-9">
        <div class="form-group">
          <div class="position-relative">
            <div class="form-group">
              {!! Form::hidden('calon2_id',$calon[1]['id']) !!}
              {!! Form::text('nama_calon2',$calon[1]['id'].'. '.$calon[1]['nama_calon_1'] .' - '. $calon[1]['nama_calon_2'],['class' =>
              'form-control','id' =>'calon-add', 'placeholder' => 'Suara','readonly']) !!}
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="form-group">
          <div class="position-relative">
            <div class="form-group">
              {!! Form::number('suara2',old('suara2') ?? '',['class' => 'form-control','id' =>'suara'.$calon[1]['id'],'placeholder' =>
              'Suara']) !!}
              <div class="form-control-position">
                <i class="bx bx-calculator"></i>
              </div>
            </div>
          </div>
        </div>
      </div>
      {{--      <div class="col-md-9">--}}
      {{--        <div class="form-group">--}}
      {{--          <div class="position-relative">--}}
      {{--            <div class="form-group">--}}
      {{--              {!! Form::hidden('calon3_id',$calon[2]['id']) !!}--}}
      {{--              {!! Form::text('nama_calon3',$calon[2]['id'].'. '.$calon[2]['nama_calon_1'] .' - '. $calon[2]['nama_calon_2'],['class' =>--}}
      {{--              'form-control','id' =>'calon-add', 'placeholder' => 'Suara','readonly']) !!}--}}
      {{--            </div>--}}
      {{--          </div>--}}
      {{--        </div>--}}
      {{--      </div>--}}
      {{--      <div class="col-md-3">--}}
      {{--        <div class="form-group">--}}
      {{--          <div class="position-relative">--}}
      {{--            <div class="form-group">--}}
      {{--              {!! Form::text('suara3',old('suara3') ?? '',['class' => 'form-control','id' =>'suara'.$calon[2]['id'],'placeholder' =>--}}
      {{--              'Suara']) !!}--}}
      {{--              <div class="form-control-position">--}}
      {{--                <i class="bx bx-calculator"></i>--}}
      {{--              </div>--}}
      {{--            </div>--}}
      {{--          </div>--}}
      {{--        </div>--}}
      {{--      </div>--}}
    </div>
    <div class="form-group">
      <label for="tps-add">Suara Tidak Sah</label>
      <div class="position-relative">
        <div class="form-group">
          {!! Form::number('suara_tidak_sah','',['class' => 'form-control','id' =>'status','placeholder' => 'Input Suara Tidak Sah']) !!}
        </div>
      </div>
    </div>
    <div class="col-12 d-flex justify-content-end ">
      <button id="btnSubmit" type="submit" class="btn btn-primary mr-1 mb-1">Simpan</button>
      <button id="btnReset" type="reset" class="btn btn-light-secondary mr-1 mb-1">Reset</button>
      <button id="btnCancel" onclick="$('#modal-form').modal('hide')" type="reset" class="btn btn-light-danger mr-1 mb-1">Batal</button>
    </div>
  </div>
</form>

resources/views/pages/hitung-cepat/partial/_form-edit.blade.php
<form class="form form-vertical" method="POST" action="{{ route('hitung-cepat.update',$id) }}">
  @method('PUT')
  @csrf
  <div class="modal-body" id="modal-body">
    <div class="row">
      <div class="col-md-5 col-12">
        <div class="form-group">
          <label for="select-kecamatan-edit">Kecamatan</label>
          <div class="position-relative">
            <div class="form-group">
              {!! Form::select('kecamatan',$kecamatan,$model->kecamatan,['class' => 'form-control selecKecEdit select2','id' =>
              'select-kecamatan-edit']) !!}
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-4 col-12">
        <div class="form-group">
          <label for="select-desa-edit">Kelurahan</label>
          <div class="position-relative">
            <div class="form-group">
              {!! Form::select('desa',$desa,$model->desa,['class' => 'form-control selectDesaEdit select2','id' => 'select-desa-edit']) !!}
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="form-group">
          <label for="tps-edit">TPS</label>
          <div class="position-relative">
            <div class="form-group">
              {!! Form::number('tps',$model->no_tps,['class' => 'form-control','id' =>'tps-edit','placeholder' => 'TPS']) !!}
              <div class="form-control-position">
                <i class="bx bx-building"></i>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-9">
        <div class="form-group">
          <label for="calon-edit">Nama Pasangan Calon</label>
          <div class="position-relative">
            <div class="form-group">
              {!! Form::hidden('calon1_id',$calon[0]['id']) !!}
              {!! Form::text('nama_calon1',$calon[0]['id'].'. '.$calon[0]['nama_calon_1'] .' - '. $calon[0]['nama_calon_2'],['class' =>
              'form-control','id' =>'calon-edit','placeholder' => 'Suara','readonly']) !!}
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="form-group">
          <label for="suara1">Jumlah Suara</label>
          <div class="position-relative">
            <div class="form-group">
              {!! Form::number('suara1',old('suara1') ?? $model->suara1,['class' => 'form-control','id' =>'suara'.$calon[0]['id'],'placeholder' =>
              'Suara']) !!}
              <div class="form-control-position">
                <i class="bx bx-calculator"></i>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-9">
        <div class="form-group">
          <div class="position-relative">
            <div class="form-group">
              {!! Form::hidden('calon2_id',$calon[1]['id']) !!}
              {!! Form::text('nama_calon2',$calon[1]['id'].'. '.$calon[1]['nama_calon_1'] .' - '. $calon[1]['nama_calon_2'],['class' =>
              'form-control','id' =>'calon', 'placeholder' => 'Suara','readonly']) !!}
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="form-group">
          <div class="position-relative">
            <div class="form-group">
              {!! Form::number('suara2',old('suara2') ?? $model->suara2,['class' => 'form-control','id' =>'suara'.$calon[1]['id'],'placeholder' =>
              'Suara']) !!}
              <div class="form-control-position">
                <i class="bx bx-calculator"></i>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="form-group">
      <label for="status-edit">Suara Tidak Sah</label>
      <div class="position-relative">
        <div class="form-group">
          {!! Form::number('suara_tidak_sah',$model->suara_tidak_sah,['class' => 'form-control','id' =>'status-edit','placeholder' => 'Input Suara
          Tidak
          Sah']) !!}
        </div>
      </div>
    </div>
    <div class="col-12 d-flex justify-content-end ">
      <button id="btnSubmit" type="submit" class="btn btn-primary mr-1 mb-1">Simpan</button>
      <button id="btnReset" type="reset" class="btn btn-light-secondary mr-1 mb-1">Reset</button>
      <button id="btnCancel" onclick="$('#modal-form').modal('hide')" type="reset" class="btn btn-light-danger mr-1 mb-1">Batal</button>
    </div>
  </div>
</form>

resources/views/pages/hitung-cepat/partial/scripts.blade.php
<script type="text/javascript">
  function formatSuaraCalon(result) {
    if (result.loading) return result.text;
    let tpl = '<span><b>' + result.text + '</b></span><br><small>' + result.info + '</small>';
    return tpl;
  }

  function formatKota(result) {
    if (result.loading) return result.text;
    let tpl = '<span><b>' + result.text + '</b></span><br><small>' + result.name
      + '</small>'
    return tpl;
  }

  function formatDefault(result) {
    if (!result.id) return result.text;
    let tpl = $('<span><b>' + result.text + '</b></span>');
    return tpl;
  }

  function setTemplate(tipe) {
    let tpl = '';
    switch (tipe) {
      case 'suaracalon':
        tpl = formatSuaraCalon;
        break;
      case 'kota':
        tpl = formatKota;
        break;
      default:
        tpl = formatDefault;
        break;
    }
    return tpl;
  }

  // Loading remote data

  function kecamatanChange(param) {
    if (param === 'edit') {
      $("#select-kecamatan-edit").change(function () {
        let selectDesa = $("#select-desa-edit");
        selectDesa.prop("disabled", false);
        return renderSelect(selectDesa, "{!! route('select.desa') !!}", setTemplate('kota'), 'Pilih Kelurahan/Desa', $("#select-kecamatan-edit").find
        (':selected').val());
      });
    } else {
      $("#select-kecamatan-add").change(function () {
        let selectDesa = $("#select-desa-add");
        selectDesa.prop("disabled", false);
        return renderSelect(selectDesa, "{!! route('select.desa') !!}", setTemplate('kota'), 'Pilih Kelurahan/Desa', $("#select-kecamatan-add").find
        (':selected').val());
      });
    }
  }

  function desaChange(param) {
    if (param !== 'edit') {
      $("#select-desa-add").change(function () {
        let fieldTps = $("#tps-add");
        fieldTps.prop("disabled", false);
      });
    } else {
      $("#select-desa-edit").change(function () {
        let fieldTps = $("#tps-edit");
        fieldTps.prop("disabled", false);
      });
    }
  }

  function tpsChange(param) {
    let id = $("#tps-add");
    if (param === 'edit') {
      id = $("#tps-edit");
    }

    id.focusin(function () {
      let suara1 = $("#suara1");
      suara1.prop("disabled", false);
    });
  }

  function tpsEditChange() {
    $("#tps-edit").focusin(function () {
      let suara1 = $("#suara1");
      suara1.prop("disabled", false);
    });
  }

  function suara1Change() {
    $("#suara1").focusin(function () {
      let suara2 = $("#suara2");
      suara2.prop("disabled", false);
    });
  }

  function suara2Change() {
    $("#suara2").focusin(function () {
      let status = $("#status");
      status.prop("disabled", false);
    });
  }

  function disabledSelect() {
    $("#tps-add").prop("disabled", true);
    $("#tps-edit").prop("disabled", true);
    $("#status").prop("disabled", true);
    $("#status-edit").prop("disabled", true);
    $("#calon-1").prop("disabled", true);
    $("#calon-2").prop("disabled", true);
    $("#suara1").prop("disabled", true);
    $("#suara2").prop("disabled", true);
    $("#select-desa-add").prop("disabled", true);
    $("#select-desa-edit").prop("disabled", true);
  }

  function renderSelect(selectInit, url, tpl, placehld, param) {
    return selectInit.select2({
      dropdownParent: $('#modal-form .modal-content'),
      dropdownAutoWidth: true,
      width: '100%',
      closeOnSelect: true,
      selectOnClose: false,
      allowClear: true,
      // minimumInputLength: 1,
      // maximumInputLength: 20,
      minimumResultsForSearch: 15,
      placeholder: placehld,
      ajax: {
        url: url,
        delay: 250,
        dataType: 'json',
        data: function (params) {
          let query = {
            q: params.term,
            i: param,
            type: 'public',
            page: params.page || 1
          };
          return query;
        },
        processResults: function (data, params) {
          params.page = params.page || 1;

          return {
            results: data.results,
            pagination: {
              more: (params.page * 15) < data.total_count
            }
          };
        },
        cache: true
      },
      escapeMarkup: function (markup) {
        return markup;
      },
      templateResult: tpl,
    });
  }

  /* Modal Show Global */
  $(document).ready(function () {
    $('body').on('click', '.modal-loader', function (e) {
      e.preventDefault();

      let me = $(this),
        url = me.data('url'),
        title = me.attr('title');

      $('#modalStyle').addClass('modal-lg');
      $('#modalTitle').text(title);

      $.ajax({
        url: url,
        dataType: 'html',
        success: function (response) {
          $('#modal-fill').html(response);
          // disabledSelect();
          renderSelect($("#select-kecamatan-add"), '{!! route('select.kecamatan') !!}', setTemplate('kota'), 'Pilih Kecamatan');
          renderSelect($("#select-kecamatan-edit"), '{!! route('select.kecamatan') !!}', setTemplate('kota'), 'Pilih Kecamatan');
          renderSelect($("#select-desa-add"), '{!! route('select.desa') !!}', setTemplate('kota'), 'Pilih Kelurahan/Desa');
          renderSelect($("#select-desa-edit"), '{!! route('select.desa') !!}', setTemplate('kota'), 'Pilih Kelurahan/Desa');
          kecamatanChange();
          kecamatanChange('edit');

          desaChange();
          desaChange('edit');

          tpsChange();
          tpsChange('edit');
          suara1Change();
          suara2Change();
        },
      });

      $('#modal-form').modal('show');
    })
  });
</script>